### ISSUE TITLE
Add OGP meta tags

### ISSUE THREAD

**Issue by c-bata** [pyconjp/pycon.jp.2019#19]
開発おつかれさまです。
スマホでもPCでもすごいきれいなサイトで驚きました。

OGPの設定が無いのが気になったので報告いたします。

**Twitter**

![スクリーンショット 2019-08-02 16 42 56](https://user-images.githubusercontent.com/5564044/62353032-9b55b600-b544-11e9-949a-dd047934976f.png)

**Slack**

![スクリーンショット 2019-08-02 16 42 43](https://user-images.githubusercontent.com/5564044/62353039-9d1f7980-b544-11e9-8e84-7f93f3c8c154.png)

**Comment by ikedaosushi** [comment]
@c-bata ありがとうございます！対応します🙇

**Comment by ikedaosushi** [comment]
遅くなってしまいましたが対応しました。ご指摘ありがとうございました！
<img width="349" alt="Slack___t-system___PyCon_JP" src="https://user-images.githubusercontent.com/4068610/64109874-8fffdf80-cdbb-11e9-83d6-3261a55132d6.png">
