### ISSUE TITLE
ヘッダー

### ISSUE THREAD

**Issue by ikedaosushi** [pyconjp/pycon.jp.2019#6]
ヘッダーのオプションのデザインを適応

#### components
`components/parials/Header.vue`

#### データ
デザインを参考
`locales` フォルダに記載

#### デザイン
https://drive.google.com/drive/folders/1Mn9pYBkelZx5p05TypZJyyh2anPXCjmO

**Comment by sudame** [comment]
## First Release
モバイル版はハンバーガボタンを隠しておく
デスクトップ版は表示項目を減らす
